module.exports = [
  'Aesthetics and Beauty Therapy',
  'Allied Medical Sciences',
  'Applied Arts',
  'Architecture',
  'Automobile Engineering',
  'Banking, Financial Services & Insurance',
  'Business Administration',
  'Business Process Management',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Computer Science and Application',
  'Data Analytics',
  'Electrical Engineering',
  'Electronics Engineering',
  'English Communication Skills',
  'Facilities & Hygiene Management',
  'Fashion Design and Technology',
  'Instrumentation & Control Engineering',
  'Interior Design',
  'Library and Information Science',
  'Mathematics',
  'Mechanical and Automation Engineering',
  'Mechanical Engineering',
  'Mechatronics',
  'Medical Lab Technology',
  'Pharmacy',
  'Physics',
  'Printing Technology',
  'Spanish',
  'Tool Engineering',
]
